### ISSUE TITLE
1.16.5能力无法显示

### ISSUE THREAD

**Issue by kitUIN** [FledgeXu/BosonSourceCode#1]
所使用版本号如下图显示
![image](https://user-images.githubusercontent.com/68675068/124153469-0c060400-dac7-11eb-8531-bebd88e39bd3.png)
代码原封如下
![image](https://user-images.githubusercontent.com/68675068/124153542-1de7a700-dac7-11eb-870b-f4676d86d0bc.png)
游戏中显示如下
![image](https://user-images.githubusercontent.com/68675068/124153575-263fe200-dac7-11eb-8ef7-efa88b99df24.png)

解决办法一:
![image](https://user-images.githubusercontent.com/68675068/124153629-348dfe00-dac7-11eb-8b0c-a310a046af9c.png)
显示正常
![image](https://user-images.githubusercontent.com/68675068/124153669-3fe12980-dac7-11eb-9099-1df462a8fa28.png)

**Comment by FledgeXu** [comment]
对Mod开发目前没什么大兴趣，没动力改。所以请发PR……
